import { ddResultItems } from '../data';

// case 6
export const ddResult: ddResultItems = {
  info: {
    projectFullName: 'this is Project Name',
    regressionUuid: '123-456',
    revision: 'bfc',
    filePath: '/dome/test',
    allHunks: [
      {
        hunkId: 'hunkId_1',
        oldCode: 'this is old code 1',
        newCode: 'this is new Code 1',
      },
      {
        hunkId: 'hunkId_2',
        oldCode: 'this is old code 2',
        newCode: 'this is new Code 2',
      },
      {
        hunkId: 'hunkId_3',
        oldCode: 'this is old code 3',
        newCode: 'this is new Code 3',
      },
      {
        hunkId: 'hunkId_4',
        oldCode: 'this is old code 4',
        newCode: 'this is new Code 4',
      },
      {
        hunkId: 'hunkId_5',
        oldCode: 'this is old code 5',
        newCode: 'this is new Code 5',
      },
      {
        hunkId: 'hunkId_6',
        oldCode: 'this is old code 6',
        newCode: 'this is new Code 6',
      },
    ],
  },
  steps: [
    {
      stepNum: 1,
      testResult: 'failed',
      testedHunks: [],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.213',
          hunkId_2: '0.213',
          hunkId_3: '0.213',
          hunkId_4: '0.213',
          hunkId_5: '0.213',
          hunkId_6: '0.213',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.1',
          hunkId_2: '0.1',
          hunkId_3: '0.1',
          hunkId_4: '0.1',
          hunkId_5: '0.1',
          hunkId_6: '0.1',
        },
      ],
    },
    {
      stepNum: 2,
      testResult: 'failed',
      testedHunks: ['hunkId_1', 'hunkId_4'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.213',
          hunkId_2: '0.345',
          hunkId_3: '0.345',
          hunkId_4: '0.213',
          hunkId_5: '0.345',
          hunkId_6: '0.345',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.1',
          hunkId_2: '0.1',
          hunkId_3: '0.1',
          hunkId_4: '0.1',
          hunkId_5: '0.1',
          hunkId_6: '0.1',
        },
      ],
    },
    {
      stepNum: 3,
      testResult: 'CE',
      testedHunks: ['hunkId_2', 'hunkId_4', 'hunkId_5', 'hunkId_6'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.213',
          hunkId_2: '0.345',
          hunkId_3: '0.345',
          hunkId_4: '0.213',
          hunkId_5: '0.345',
          hunkId_6: '0.345',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.3',
          hunkId_2: '0.1',
          hunkId_3: '0.3',
          hunkId_4: '0.1',
          hunkId_5: '0.1',
          hunkId_6: '0.1',
        },
      ],
    },
    {
      stepNum: 4,
      testResult: 'CE',
      testedHunks: ['hunkId_2', 'hunkId_3', 'hunkId_4', '    hunkId_5'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.213',
          hunkId_2: '0.345',
          hunkId_3: '0.345',
          hunkId_4: '0.213',
          hunkId_5: '0.345',
          hunkId_6: '0.345',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.5',
          hunkId_2: '0.1',
          hunkId_3: '0.3',
          hunkId_4: '0.1',
          hunkId_5: '0.1',
          hunkId_6: '0.3',
        },
      ],
    },
    {
      stepNum: 5,
      testResult: 'CE',
      testedHunks: ['hunkId_1', 'hunkId_2', 'hunkId_3', ' hunkId_6'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.213',
          hunkId_2: '0.345',
          hunkId_3: '0.345',
          hunkId_4: '0.213',
          hunkId_5: '0.345',
          hunkId_6: '0.345',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.5',
          hunkId_2: '0.1',
          hunkId_3: '0.3',
          hunkId_4: '0.3',
          hunkId_5: '0.3',
          hunkId_6: '0.3',
        },
      ],
    },
    {
      stepNum: 6,
      testResult: 'pass',
      testedHunks: ['hunkId_1', 'hunkId_2', 'hunkId_3', ' hunkId_4'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.213',
          hunkId_2: '0.345',
          hunkId_3: '0.345',
          hunkId_4: '0.213',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.5',
          hunkId_2: '0.1',
          hunkId_3: '0.3',
          hunkId_4: '0.3',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
      ],
    },
    {
      stepNum: 7,
      testResult: 'CE',
      testedHunks: ['hunkId_2', 'hunkId_3'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.213',
          hunkId_2: '0.345',
          hunkId_3: '0.345',
          hunkId_4: '0.213',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.6',
          hunkId_2: '0.1',
          hunkId_3: '0.3',
          hunkId_4: '0.4',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
      ],
    },
    {
      stepNum: 8,
      testResult: 'failed',
      testedHunks: ['hunkId_3', ' hunkId_4'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.439',
          hunkId_2: '0.712',
          hunkId_3: '0.345',
          hunkId_4: '0.213',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.5',
          hunkId_2: '0.1',
          hunkId_3: '0.3',
          hunkId_4: '0.4',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
      ],
    },
    {
      stepNum: 9,
      testResult: 'failed',
      testedHunks: ['hunkId_1', 'hunkId_2'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.439',
          hunkId_2: '0.712',
          hunkId_3: '0.712',
          hunkId_4: '0.439',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.5',
          hunkId_2: '0.1',
          hunkId_3: '0.2',
          hunkId_4: '0.3',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
      ],
    },
    {
      stepNum: 10,
      testResult: 'CE',
      testedHunks: ['hunkId_2', 'hunkId_3'],
      testResultData: [
        {
          resultType: 'cPro',
          hunkId_1: '0.439',
          hunkId_2: '0.712',
          hunkId_3: '0.712',
          hunkId_4: '0.439',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
        {
          resultType: 'dPro',
          hunkId_1: '0.6',
          hunkId_2: '0.1',
          hunkId_3: '0.2',
          hunkId_4: '0.4',
          hunkId_5: '0.0',
          hunkId_6: '0.0',
        },
      ],
    },
  ],
};

export const hunkRelationData = {};
